DIALOGUES = {
    "学姐": [
        {
            "text": "你是新来的吧？画画过吗？", 
            "optionA": "其实我更擅长写代码，但我愿意试试画画。",
            "optionB": "画画？那种小孩子的东西我可没兴趣。",
            "optionA_effect": 10,
            "optionB_effect": -15,
            "weight": 1,
            "requires_affinity": 0,
            "high_affinity_only": False,
        },
        {
            "text": "这幅画……构图还算不错，你是随便画的吗？", 
            "optionA": "嗯，我是随手画的，没想到能得到你的认可。",
            "optionB": "不，我可是很认真的！因为你在看嘛。",
            "optionA_effect": 5,
            "optionB_effect": 8,
            "weight": 2,
            "requires_affinity": 0,
            "high_affinity_only": False,
        },
        {
            "text": "加入社团后，不能三天打鱼两天晒网。", 
            "optionA": "放心吧，我会认真对待。",
            "optionB": "社团只是玩玩而已吧？不要太严肃了。",
            "optionA_effect": 10,
            "optionB_effect": -10,
            "weight": 1,
            "requires_affinity": 10,
            "high_affinity_only": False,
        },
        {
            "text": "我平时比较严格，你会不会觉得我很不好相处？", 
            "optionA": "严格才好啊，我喜欢有目标的人。",
            "optionB": "嗯……确实有点难相处。",
            "optionA_effect": 15,
            "optionB_effect": -20,
            "weight": 1,
            "requires_affinity": 20,
            "high_affinity_only": False,
        },
        {
            "text": "今天的社团活动结束了，你要不要和我一起收拾？", 
            "optionA": "当然可以，我来帮你。",
            "optionB": "算了吧，我还有事要做。",
            "optionA_effect": 10,
            "optionB_effect": -10,
            "weight": 1,
            "requires_affinity": 30,
            "high_affinity_only": False,
        },
        {
            "text": "其实我一直在关注你的作品...", 
            "optionA": "真的吗？我很高兴你能喜欢。",
            "optionB": "哦，是吗？",
            "optionA_effect": 20,
            "optionB_effect": -5,
            "weight": 1,
            "requires_affinity": 50,
            "high_affinity_only": True,
        }
    ],
    "小白": [
        {
            "text": "Python 里的 for 循环，我总是写不对……", 
            "optionA": "来，我教你一个小技巧！",
            "optionB": "这种简单的东西，你都不会？",
            "optionA_effect": 10,
            "optionB_effect": -15,
            "weight": 2,
            "requires_affinity": 0,
            "high_affinity_only": False,
        },
        {
            "text": "你看我借了好多书，会不会显得很傻？", 
            "optionA": "不会啊，这说明你很爱学习，很可爱。",
            "optionB": "嗯……的确有点太贪心了。",
            "optionA_effect": 15,
            "optionB_effect": -10,
            "weight": 1,
            "requires_affinity": 10,
            "high_affinity_only": False,
        },
        {
            "text": "写代码的时候，我总喜欢喝奶茶……你呢？", 
            "optionA": "我也是！来，下次我请你一杯。",
            "optionB": "我只喝水，健康第一。",
            "optionA_effect": 10,
            "optionB_effect": -5,
            "weight": 1,
            "requires_affinity": 20,
            "high_affinity_only": False,
        },
        {
            "text": "你会不会觉得我太依赖你了？", 
            "optionA": "依赖我也没关系，我喜欢这种感觉。",
            "optionB": "嗯……是有点吧。",
            "optionA_effect": 15,
            "optionB_effect": -15,
            "weight": 1,
            "requires_affinity": 30,
            "high_affinity_only": False,
        },
        {
            "text": "要不要一起留在图书馆自习？我想有人陪。", 
            "optionA": "好啊，我正好也要复习。",
            "optionB": "算了，我还是回宿舍打游戏吧。",
            "optionA_effect": 10,
            "optionB_effect": -10,
            "weight": 1,
            "requires_affinity": 40,
            "high_affinity_only": False,
        },
        {
            "text": "其实...我一直觉得你很厉害，想多和你学习", 
            "optionA": "我也很喜欢和你一起学习。",
            "optionB": "嗯，我知道。",
            "optionA_effect": 20,
            "optionB_effect": 0,
            "weight": 1,
            "requires_affinity": 60,
            "high_affinity_only": True,
        }
    ],
    "姐姐": [
        {
            "text": "你也喜欢在咖啡店看书吗？", 
            "optionA": "是啊，这里很安静，很适合思考。",
            "optionB": "其实我只是随便找个地方坐。",
            "optionA_effect": 10,
            "optionB_effect": -5,
            "weight": 2,
            "requires_affinity": 0,
            "high_affinity_only": False,
        },
        {
            "text": "研究生的生活，其实没有你想象的那么光鲜。", 
            "optionA": "我能理解，压力一定很大吧。",
            "optionB": "那我还是不要考研了。",
            "optionA_effect": 15,
            "optionB_effect": -10,
            "weight": 1,
            "requires_affinity": 10,
            "high_affinity_only": False,
        },
        {
            "text": "你觉得，什么样的人最值得依靠？", 
            "optionA": "稳重冷静的人。",
            "optionB": "长得好看的人。",
            "optionA_effect": 10,
            "optionB_effect": -15,
            "weight": 1,
            "requires_affinity": 20,
            "high_affinity_only": False,
        },
        {
            "text": "我常常一个人坐到很晚，你不会觉得孤单吗？", 
            "optionA": "有时候孤单是种享受。",
            "optionB": "一个人太寂寞了，我受不了。",
            "optionA_effect": 15,
            "optionB_effect": -5,
            "weight": 1,
            "requires_affinity": 30,
            "high_affinity_only": False,
        },
        {
            "text": "如果有一天，我遇到困难，你会帮我吗？", 
            "optionA": "当然会，你不用一个人扛着。",
            "optionB": "我大概帮不了你吧。",
            "optionA_effect": 20,
            "optionB_effect": -20,
            "weight": 1,
            "requires_affinity": 40,
            "high_affinity_only": False,
        },
        {
            "text": "和你在一起的时候，我感觉很安心...", 
            "optionA": "我也是，和你在一起很舒服。",
            "optionB": "是吗？谢谢。",
            "optionA_effect": 25,
            "optionB_effect": 5,
            "weight": 1,
            "requires_affinity": 70,
            "high_affinity_only": True,
        }
    ]
}

GIFT_EFFECTS = {
    # 通用 / 默认 值
    "鲜花": {"学姐": 10, "小白": 10, "姐姐": 15},
    "编程笔记": {"学姐": 5, "小白": 15, "姐姐": 15},
    "奶茶": {"学姐": 20, "小白": 20, "姐姐": 20},
    "奇怪的石头": {"default": -10},  # 所有人 -10
    "精致的钢笔": {"学姐": 20, "小白": 10, "姐姐": 20},
    "可爱玩偶": {"学姐": 10, "小白": 20, "姐姐": 10},
    "夜宵外卖": {"学姐": 0, "小白": 5, "姐姐": -5}
}